#http://192.168.99.100:8888/assets/index.html#/weight
version: "2"
services:
  db:
    image: finatra/couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  app:
    stdin_open: true
    tty: true
    image: finatra/app
    environment:
      - couchbase=db
    ports:
      - 8888:8888

